trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'terraform/infrastructure' 

stages:

- template: terraform-stages-template.yml
  parameters:
    resourcegroup: apt-dev-uks-rg
    terraformVersion: 0.14.5
    environment: Dev

- template: terraform-stages-template.yml
  parameters:
    resourcegroup: apt-uat-uks-rg
    terraformVersion: 0.14.5
    environment: UAT

- template: terraform-stages-template.yml
  parameters:
    resourcegroup: apt-prod-uks-rg
    terraformVersion: 0.14.5
    environment: Prod